### ISSUE TITLE
Decimal('4294967310') gets rendered as 4294967310.0

### ISSUE THREAD

**Issue by df7cb** [lelit/pglast#100]
Integer literals > 2^31 get parsed as Decimal which gets incorrectly .0 appended when rendered back:

```
>>> RawStream()(pglast.parse_sql('select 4294967310'))
'SELECT 4294967310.0'
```

That is a problem if the query is actually expecting a bigint.
* PG15 regression testsuite: `SELECT lo_put(33349, 4294967310, 'foo');`
* Query when piped though pglast/pgpp: `SELECT lo_put(33349, 4294967310.0, 'foo')`
* `ERROR:  function lo_put(integer, numeric, unknown) does not exist`

**Comment by lelit** [comment]
Thanks for the report!

**Comment by lelit** [comment]
Should be fixed as well!

**Comment by lelit** [comment]
Released in v3.9.

**Comment by df7cb** [comment]
Thanks for the fixes and the new release!

Fwiw I've build pglast packages for apt.postgresql.org, called python3-pglast there.

They are not in Debian/main yet as that has already moved to PostgreSQL 14 and the required PG13 server headers aren't available anymore, but I'll fix that as soon there is a libpg-query + pglast supporting that.

Cheers,
Christoph

**Comment by lelit** [comment]
Thank you!
