### ISSUE TITLE
Support PG 14

### ISSUE THREAD

**Issue by sgreene570** [lelit/pglast#101]
This is an issue to track the work required to add full PG 14 support to pglast.

This work would be blocked by https://github.com/pganalyze/libpg_query/issues/127.

**Comment by lelit** [comment]
Thanks to the work done in https://github.com/wolfgangwalther/libpg_query/tree/pg-14 and https://github.com/tlisanti/libpg_query/tree/14-latest, the v4 branch now targets PG 14!

**Comment by lelit** [comment]
I just released v4.0! :santa:
