### ISSUE TITLE
Extra parens when formatting different operations

### ISSUE THREAD

**Issue by johnny-ppl-ai** [lelit/pglast#109]
An extra set of parens is printed when formatting the following:
```
print(pglast.prettify("SELECT a+b-c/d"))
SELECT ((a + b)) - ((c / d))
```
Was wondering if this is required or a stylistic choice? Logic at https://github.com/lelit/pglast/blob/c97de80bfcb66a2f4c047fb61e7df20b6f98e40e/pglast/printers/dml.py#L101

Perhaps it's safe to reduce the check to `if node.lexpr.kind == node.kind:` since there will be parens.

**Comment by lelit** [comment]
It is not that easy to remove extra parens, the approach I took was "stay simple and safe". But yes, it annoyed me as well, and so in v4 I slightly [improved the logic](https://github.com/lelit/pglast/commit/060d20da56f7488f67ee53bd840c7a4cac0e2f26):

```python
>>> print(pglast.prettify("SELECT a+b-c/d"))
SELECT (a + b) - (c / d)
```

**Comment by johnny-ppl-ai** [comment]
thanks, looking forward to v4!
