### ISSUE TITLE
Deparsing of modified queries and query parts

### ISSUE THREAD

**Issue by chatumao** [lelit/pglast#116]
Hello, first of all thank you very much for this nice software! 
I wondered if it is possible to do as the title says.
Something like it is done here: https://pganalyze.com/blog/pg-query-2-0-postgres-query-parser#turning-parse-trees-back-into-sql-using-a-deparser as an example for a modified query. I would, however, also be interested in just passing a part of a query. For example passing a ResTarget object to a function that would just return the SQL of that part.
I searched in the source code of pg_query, but all I could find in terms of deparsing was the pg_query_deparse_protobuf function, which is already exposed in pglast.

**Comment by lelit** [comment]
Try something like this:
```python
import pglast
root = pglast.parse_sql('select (select a + 1) from b')
restarget = root[0].stmt.targetList[0]
print(restarget)
# <ResTarget val=<SubLink subLinkType=<SubLinkType.EXPR_SUBLINK: 4> subLinkId=0 subselect=<SelectStmt targetList=(<ResTarget val=<A_Expr kind=<A_Expr_Kind.AEXPR_OP: 0> name=(<String val='+'>,) lexpr=<ColumnRef fields=(<String val='a'>,)> rexpr=<A_Const val=<Integer val=1>>>>,) groupDistinct=False limitOption=<LimitOption.LIMIT_OPTION_DEFAULT: 0> op=<SetOperation.SETOP_NONE: 0> all=False>>>
from pglast.stream import IndentedStream
import pglast.printers
print(IndentedStream()(restarget))
# (SELECT a + 1)
```

**Comment by chatumao** [comment]
That works, thanks!

**Comment by lelit** [comment]
You're welcome!
