### ISSUE TITLE
Cookbook of common format styles

### ISSUE THREAD

**Issue by ghost** [lelit/pglast#16]
Very cool project.

I've been looking at pglast and [`sqlfmt`](https://www.cockroachlabs.com/blog/sql-fmt-online-sql-formatter/) tool ([demo](https://sqlfum.pt/?n=48&indent=4&spaces=1&simplify=1&align=0&case=upper&sql=U0VMRUNUIGNvdW50KCopIEFTIGNvdW50LAogICAgICAgd2lubmVyLAogICAgICAgKGNvdW50ZXIgKiA2MCkgKiA1IEFTIGNvdW50ZXIKRlJPTSAoU0VMRUNUIHdpbm5lciwKCSAgICAgcm91bmQobGVuZ3RoIC8gKDYwICogNSkpIEFTIGNvdW50ZXIKICAgICAgRlJPTSBwbGF5ZXJzCiAgICAgIFdIRVJFIChidWlsZCA9ICQxKQoJQU5EICgoICAgKGhlcm8gPSAkMikKCSAgICAgIE9SIChyZWdpb24gPSAkMykpKSkgQVMgcwpHUk9VUCBCWSB3aW5uZXIsIGNvdW50ZXIK). I'm hoping to use pglast on my projects.

I know people have lots of different style preferences, and each auto-formatter must decide on configurability (like [yapf](https://github.com/google/yapf)) vs consistency (like [black](https://github.com/ambv/black)).

I'm still developing my taste in SQL formatting, but to my own eye, a couple features of sqlfmt's style can make code easier to read.

- the argument list of `SELECT`, `FROM`, etc. appear on the next line, indented
- parentheses delimiting a subquery get their own line and the body of the subquery is indented inside

```sql

SELECT
    count(*) AS count,
    winner,
    counter * 60 * 5 AS counter
FROM
    (
        SELECT
            winner,
            round(length / (60 * 5)) AS counter
        FROM
            players
        WHERE
            build = $1
            AND ((hero = $2 OR region = $3))
    )
        AS s
GROUP BY
    winner, counter;
```
compare pgpp 1.2:

```sql
SELECT count(*) AS count,
       winner,
       (counter * 60) * 5 AS counter
FROM (SELECT winner,
	     round(length / (60 * 5)) AS counter
      FROM players
      WHERE (build = $1)
	AND ((   (hero = $2)
	      OR (region = $3)))) AS s
GROUP BY winner, counter
```

I'd like to configure my pgpp to add newlines and indentation. How would you feel about adding such options, or adding a cookbook with a few examples on how to make these adjustments?

Thanks very much for sharing the project!

**Comment by lelit** [comment]
It's not that complicated to obtain different styles: what is really difficult is to satisfy everybody :-)

One could go with *printer options*, like what I did with [comma_at_eoln](pglast/printer.py#L189), or more rudely reimplement one or more printers, until your eyes are satisfied. In the specific case, you want to alter the [SelectStatement](pglast/printers/dml.py#L693) printer, using a different way to emit its `targetList` node.

I'll be happy to be of further help, if you need.

**Comment by KangOl** [comment]
I like the alignment proposed by https://www.sqlstyle.guide/

**Comment by lelit** [comment]
Nice reference, thank you.

**Comment by lelit** [comment]
I'm closing this, as it is unlikely that a generic way to configure printers _aesthetic sense_ will land here.
