### ISSUE TITLE
CTE query when using RawStream outputs without a space

### ISSUE THREAD

**Issue by edinpeter** [lelit/pglast#163]
This change here seems intended to hit the highly indented print flow using CTEs to make them cleaner looking: https://github.com/lelit/pglast/commit/6cc843c7c8d175ba21bf38cd9ab8a156a3d42692

However, it also had the (maybe) unintended side effect of also removing spaces when using RawStream:

Before:
```
WITH cte AS (SELECT *...
```
After:
```
WITH cte AS(SELECT *...
```
Was this intentional? If not could the change be undone / handled better?

**Comment by lelit** [comment]
Ouch, no, it was not intentional! Thank you for the report, I will rectify that as soon as possible.

**Comment by edinpeter** [comment]
Awesome thanks!

**Comment by lelit** [comment]
This should be fixed in the just released v6.9.
