### ISSUE TITLE
How to get individual tags from AST Tree

### ISSUE THREAD

**Issue by ck090** [lelit/pglast#21]
I would like to understand the output of the following line of code.
`for nodes in root.traverse():
...     print(nodes)
`
I understand it gives me an AST Tree, but how can I interpret it to get meaningful information out like, column names, inner join condition, inner join table name, where clause etc..
For example: When I run
`sql2 = 'select * from mj inner join jimmy on jimmy.eyes = mj.eyes'`
`root = Node(parse_sql(sql2))`
I get the following output
`None[0]={RawStmt}`
`stmt={SelectStmt}`
`fromClause[0]={JoinExpr}`
`jointype=<0>`
`larg={RangeVar}`
`inh=<True>`
`location=<14>`
`relname=<'mj'>`
`relpersistence=<'p'>`
`quals={A_Expr}`
`kind=<0>`
`lexpr={ColumnRef}`
`fields[0]={String}`
`str=<'jimmy'>`
`fields[1]={String}`
`str=<'eyes'>`
`location=<37>`
`location=<48>`
`name[0]={String}`
`str=<'='>`
`rexpr={ColumnRef}`
`fields[0]={String}`
`str=<'mj'>`
`fields[1]={String}`
`str=<'eyes'>`
`location=<50>`
`rarg={RangeVar}`
`inh=<True>`
`location=<28>`
`relname=<'jimmy'>`
`relpersistence=<'p'>`
`op=<0>`
`targetList[0]={ResTarget}`
`location=<7>`
`val={ColumnRef}`
`fields[0]={A_Star}`
`location=<7>`
Can someone make me understand this. Thanks

**Comment by lelit** [comment]
I'm afraid the only way is to learn a bit about the internal representation that the PG parser builds: thanks to the underlying libpgquery, what you see is actually a serialized representation of that.

The documentation lists all implemented *nodes*, with a reference to the PG header that define the related structure.
