### ISSUE TITLE
Semicolon at the end is deleted

### ISSUE THREAD

**Issue by apnewberry** [lelit/pglast#24]
From master

```
pgpp <<EOF
SELECT 1;
SELECT 2;
EOF

```
output:

```
SELECT 1;

SELECT 2
```

I'd like to keep the final semicolon if possible.

**Comment by lelit** [comment]
Yes, that would be probably better and without drawbacks. It would touch the same code as #25.
Any chance you could offer a PR? :smile_cat:

**Comment by lelit** [comment]
This will be released in the next version, sorry.

**Comment by lelit** [comment]
Release in version 1.8.
