### ISSUE TITLE
Two lines between statements?

### ISSUE THREAD

**Issue by apnewberry** [lelit/pglast#25]
To my eye, it's a little nicer for long statements to have two lines between them, not just one. It helps visually separate them from each other. What do you think?

**Comment by lelit** [comment]
What do you mean with _long statements_?

**Comment by lelit** [comment]
If you mean _whole statements_, it would be quite easy to do: maybe changing [separate_statements](https://github.com/lelit/pglast/blob/master/pglast/printer.py#L183) from `bool` to `int`, and using it to emit _that_ count of newlines [here](https://github.com/lelit/pglast/blob/master/pglast/printer.py#L230).
