### ISSUE TITLE
Add support for psql variables

### ISSUE THREAD

**Issue by fpuga** [lelit/pglast#34]
I frequently use [psql variables](https://www.postgresql.org/docs/current/app-psql.html#APP-PSQL-VARIABLES) in my scripts.

It will be awesome if pglast can support then.

```
$ echo "ALTER FUNCTION myschema.myfunction OWNER TO :owner;" | pgpp

syntax error at or near ":", at location 45
```

**Comment by lelit** [comment]
Unfortunately I think that's a `psql` extension: the standard parameter placeholder is `$n` with `n` being a positive integer... but even that works only for some statements:
```
$ echo 'DELETE FROM extensions WHERE values[0] = $1' | pgpp
DELETE FROM extensions
WHERE (values)[0] = $1
```
There's little I can do, without support in the underlying [libpg_query](https://github.com/lfittl/libpg_query) parser, sorry.

**Comment by fpuga** [comment]
It's a shame, but thanks for the answer.
