### ISSUE TITLE
Feature request: Reformat SQL in Python files

### ISSUE THREAD

**Issue by dms-cat** [lelit/pglast#37]
It would be a killer feature if this could be extended to [reformat Python source files in place](https://github.com/psf/black/issues/1185), similar to what Black does.

**Comment by lelit** [comment]
I don't know how Black operates, but the harder part would be to come up with a good heuristic to identify SQL strings in the source, then calling pglast isn't that difficult, no?

OTOH, do you really have all those SQL literal statements scattered through your sources?
In my case, I almost always rely on SQLAlchemy to build them with obvious benefits, last but not least that I can document *almost static* statements and pretty print them using [Sphinx](https://pypi.org/project/metapensiero.sphinx.autodoc-sa/)...

**Comment by dms-cat** [comment]
@lelit ORMs are fine for simple CRUD logic, but when trying to map from a legacy database to a new one, using foreign data wrappers and database-specific features like `PARTITION BY` they usually don't support them or you need to be an expert in both SQL *and* the ORM to have a chance. Raw SQL ended up being easier and orders of magnitude faster.

**Comment by lelit** [comment]
I'm an SQL guy, and usually my complex queries are at the core layer of SA, no ORM involved.
Anyway, I get your point.

**Comment by lelit** [comment]
It just came to mind, wouldn't it be a lot simpler if your Python script loaded the SQL literal statements from external files, instead of embedding them as long strings? That would make it easier both edit (your editor would know the _major mode_ (in Emacs parlance)) and to automatically apply the prettification...

**Comment by lelit** [comment]
Closing the issue, as it is highly unlikely I will implement such feature, sorry: I still think that is a job for a different tool, something like a _plugin_ for `Black`.
