### ISSUE TITLE
Node => String

### ISSUE THREAD

**Issue by pags** [lelit/pglast#46]
Is it possible to take a root Node and "stringify" it _back_ into raw SQL?

**Comment by lelit** [comment]
Ven 14 Feb 2020, 21:13 Justin Pagano <notifications@github.com> ha scritto:

> Is it possible to take a root Node and "stringify" it *back* into raw SQL?
>
Can you clarify please? After all, it is basically what happens when you
use the prettifier tool...

Ciao, lele.

**Comment by pags** [comment]
Sure, imagine this code:

```
from pglast import Node, parse_sql

root = Node(parse_sql('SELECT foo FROM bar GROUP BY foo'))
```

Now, is there some way in Python (not CLI) to take `root` and convert it back to a string that equals 'SELECT foo FROM bar GROUP BY foo' ?

**Comment by lelit** [comment]
Sure, the `prettify` function is quite simple, see see https://github.com/lelit/pglast/blob/master/pglast/__init__.py#L45

**Comment by pags** [comment]
```
from pglast import Node, parse_sql
from pglast.printer import IndentedStream

root = Node(parse_sql('SELECT foo FROM bar GROUP BY foo'))

prettified = IndentedStream()(root)
```

throws `NotImplementedError: Printer for node 'RawStmt' is not implemented yet`

**Comment by lelit** [comment]
Sorry for the omitted detail: if you do like that, you need to to explicitly import the printers, so add something like `import pglast.printers`.
Otherwise, just use the `prettify` entry point and you are done:
```python
>>> from pglast import prettify
>>> print(prettify("SELECT foo FROM bar GROUP BY foo"))
SELECT foo
FROM bar
GROUP BY foo
```

**Comment by pags** [comment]
That works, thanks!
