### ISSUE TITLE
Support Visitor Pattern in Base class

### ISSUE THREAD

**Issue by vrajat** [lelit/pglast#51]
Visitor pattern is a common pattern to process parse trees in SQL. Very simply, there is a visitor with the following pseudo-code:

    class Visitor:
        def visit(self, node):
            if obj is None:
                return None
            if isinstance(obj, AcceptingNode):
                self.visit_node(obj)
            elif isinstance(obj, AcceptingList):
                self.visit_list(obj)
            elif isinstance(obj, AcceptingScalar):
                self.visit_scalar(obj)

      def visit_node(self):
      # Visit all the child nodes

     ....

The `Base` class in `node.py` has to have an accept function:

    def accept(self, visitor):
        visitor.visit(self)

Then other apps can build visitors to process the parse tree. I've got visitors to work in my project based on pglast:  

[node.py](https://github.com/tokern/data-lineage/blob/master/data_lineage/parser/node.py#L88) where I've added the `accept` function the `Base` class.

[Visitor Base Class](https://github.com/tokern/data-lineage/blob/master/data_lineage/parser/visitor.py) that handles navigation among children node.

[Table Visitor](https://github.com/tokern/data-lineage/blob/master/data_lineage/visitors/table_visitor.py) that collects all the table names in the SQL query. 

[Tests](https://github.com/tokern/data-lineage/blob/master/test/test_dml_visitor.py)

I can contribute the `accept` function and `Visitor` base class if you think it will be useful to other developers of your project. I can support the Visitor pattern as well.

**Comment by lelit** [comment]
Thank you Rajat. Not using something like that myself, I fail to see a possible usage, but OTOH I do not foresee a drawback in implementing the patterns.

I'm currently focused on other things, so I'm not able to study the issue: it would be great if you could open a PR, with a short explanation of the goal (or possible usages). If you do, please base it on the `v2` branch.

I will then look at it as time permits.

**Comment by vrajat** [comment]
Thanks for the reply. I’ll open a PR. On real world use cases, I already have a couple in the project linked in the original description.

**Comment by vrajat** [comment]
A few links that might give you a better idea: 
I know you are too busy to go through the links. Putting it here for later reference. I want to emphasize that there are real use cases that are built on this framework. 


Project: https://github.com/tokern/data-lineage/

Landing Page: https://tokern.io/data-lineage/

Example: https://tokern.io/docs/data-lineage/example/

Example in production: https://tokern.io/blog/data-lineage-on-redshift/

**Comment by lelit** [comment]
This is now implemented in the v3 branch.

**Comment by lelit** [comment]
Present in release v3.0.dev1
