### ISSUE TITLE
New postgres12 keyword

### ISSUE THREAD

**Issue by ak409** [lelit/pglast#57]
Hi,

CTE behaviour was changed in postgres12, so because of that there were added new keywords: "MATERIALIZED" and "NOT MATERIALIZED" for cte statements.

Examples:
```
WITH k AS MATERIALIZED (select * from m) select * from k;
WITH k AS NOT MATERIALIZED (select * from m) select from k;
```

it seems the v2 does not support this new syntax.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pglast/parser.pyx", line 75, in pglast.parser.parse_sql
pglast.parser.ParseError: syntax error at or near "MATERIALIZED", at location 11
```

Can you help with this issue?

https://www.postgresql.org/docs/12/queries-with.html

**Comment by lelit** [comment]
Thanks for reporting, I will probably take care of this in the weekend!

**Comment by lelit** [comment]
But wait, are you sure you are using the v2 branch?

This is what I get with that:
```
$ pgpp 
WITH k AS MATERIALIZED (select * from m) select * from k
WITH k AS (SELECT *
           FROM m)

  SELECT *
  FROM k
/home/lele/wip/pglast/pglast/__init__.py:61: RuntimeWarning: Detected a non-cosmetic difference between original and prettified statements, please report
  warnings.warn("Detected a non-cosmetic difference between original and"
WITH k AS MATERIALIZED (select * from m) select * from k
```

**Comment by ak409** [comment]
Possibly it was my bad, I did not switch pg_query to needed commit..

Maybe next question is not part of this issue, but maybe you faced it:

After pglast v2 was succesfully installed, I have such traceback during importing pglast or using pgpp:
```
pgpp --help
Traceback (most recent call last):
  File "/usr/local/bin/pgpp", line 5, in <module>
    from pglast.__main__ import main
  File "/usr/local/lib/python3.7/site-packages/pglast/__init__.py", line 12, in <module>
    from .parser import get_postgresql_version, parse_plpgsql, parse_sql
ImportError: /usr/local/lib/python3.7/site-packages/pglast/parser.cpython-37m-x86_64-linux-gnu.so: undefined symbol: get_array_type
```
I use official python3 docker image. The same behaviour is for python:3.8.3-buster, python:3.7.8-stretch. But master branch works correctly.

**Comment by lelit** [comment]
Does the image contain `bison` and `flex`? See commit 538890f32e472daed81ed57333dcac537be06095, that cured a similar problem in the CI machinery.

**Comment by ak409** [comment]
Cool) Thanks a lot) you are awesome)

**Comment by lelit** [comment]
Why did you close this? It's not solved yet, please let me do that when I have a solution :smile:

**Comment by ak409** [comment]
I closed because everything you told me make it work. 

Ok, I will not close it) 
So from our side we start to test our 1k+ analytical scripts with v2.  So If you need to test something on bunch of scripts, we are ready and glad to help) Just message me or Paul

**Comment by lelit** [comment]
Yes, I'm not surprised that the _parser_ works, but pglast is still not able to print the AST back.
Thanks for the help offer! FYI, I usually hangs on `#pglast` on freenode.

**Comment by lelit** [comment]
Ok, this should be fixed in the `v2` branch!

I'll gladly try to fix any further issue you may find with your substantial scripts collection :smile:
