### ISSUE TITLE
Dictionary Error when parsing plsql

### ISSUE THREAD

**Issue by sakethoppula** [lelit/pglast#61]
Getting the following error when trying to parse a plsql procedure DDL where sql is stored in a variable and executed using Execute command
Unexpected value for 'details', must be a dict with exactly one key, got <class 'dict'>

**Comment by lelit** [comment]
Any chance you could provide the statement that triggered that error?

**Comment by lelit** [comment]
Without further input it's impossible for me to understand and possibly cure the problem.
