### ISSUE TITLE
parsenodes.py enums not matching up with parse_sql output

### ISSUE THREAD

**Issue by tessa-bitdotio** [lelit/pglast#63]
Hi—really been enjoying this library 

While on branch v2 (https://github.com/lelit/pglast/tree/v2), I've been noticing some inconsistencies between the dictionaries returned by `parse_sql` and some of the enums in enums/parsenodes.py. 
As an example, the value of the attribute `'subtype'` in the `AlterTableCmd` node is supposed to reference a member of the `AlterTableType` enum in parsenodes.py. When running `parse_sql` on a drop column command, the value of `'subtype'` in the `AlterTableCmd` node is 10 (which is equal to the value of the enum member with name `AT_SetStorage`) when we were expecting 11 (which references `AT_DropColumn`)

To illustrate, when running:
```
alterStmt = 'ALTER TABLE myschema.tablename DROP dropCol'
print(parse_sql(alterStmt))
print("'subtype' returned: " + repr(AlterTableType(10)))
print("expected: " + repr(AlterTableType.AT_DropColumn))
```
the output is:

```
[{'RawStmt': {'stmt': {'AlterTableStmt': {'cmds': [{'AlterTableCmd': {'behavior': 0,
                                                                    'name': 'dropcol',
                                                                    'subtype': 10}}], <--
                                          'relation': {'RangeVar': {'inh': True,
                                                                    'location': 12,
                                                                    'relname': 'tablename',
                                                                    'relpersistence': 'p',
                                                                    'schemaname': 'myschema'}},
                                          'relkind': 37}}}}]
'subtype' returned: <AlterTableType.AT_SetStorage: 10>
expected: <AlterTableType.AT_DropColumn: 11>
```

I've also noticed similar behavior in the `ObjectType` enum, where the value returned by `parse_sql` (37) is slightly lower than the value I expected (`ObjectType.OBJECT_TABLE`, which has a value of 39). 
This suggests maybe the `parse_sql `function is referencing a different version of postgres than the enums/parsenodes.py file (which seems to match up with the PostgreSQL 12 source code) because it's missing some enum members. 
Would you be able to update this? Thanks so much!

**Comment by lelit** [comment]
You may try to use the v2 branch, that targets PG12 and where 
```
$ echo "ALTER TABLE myschema.tablename DROP dropCol" | pgpp -t
[
  {
    "RawStmt": {
      "stmt": {
        "AlterTableStmt": {
          "cmds": [
            {
              "AlterTableCmd": {
                "behavior": 0,
                "name": "dropcol",
                "subtype": 11
              }
            }
          ],
          "relation": {
            "RangeVar": {
              "inh": true,
              "location": 12,
              "relname": "tablename",
              "relpersistence": "p",
              "schemaname": "myschema"
            }
          },
          "relkind": 39
        }
      }
    }
  }
]
```
matches your expectations :stuck_out_tongue_winking_eye:

**Comment by lelit** [comment]
The master branch targets PG10.

**Comment by jmo-qap** [comment]
Ah! This was my bad. I setup the environment for @tessa-bitdotio but didn't update the submodule when I checked out the V2 branch :-( So, the enums weren't matching because the main repo was up-to-date but libpg_query was on PG10. 

Checking out the right version of the submodule and `pip install ./pglast` yields the:
```
undefined symbol: get_array_type
```
like in https://github.com/lelit/pglast/pull/36 and https://github.com/lelit/pglast/issues/57. More to come when I wakeup.

**Comment by lelit** [comment]
Are you sure you updated also the underlying submodule?

**Comment by jmo-qap** [comment]
Yep! Working now! 

Somehow, since I last installed bison and flex, they were uninstalled when I reinstalled with the submodule. I suspect a container restarted. So, mea culpa again @tessa-bitdotio and @lelit.

**Comment by lelit** [comment]
Great, feel free to suggest anything that could help clarifying the install steps.
I guess I should decide to do an actual release of v2 sooner or later...
