### ISSUE TITLE
deparsing the ast to raw string?

### ISSUE THREAD

**Issue by jinsellforte** [lelit/pglast#65]
Hi,

is there a deparse function implemented already?
thanks for the reply.

**Comment by lelit** [comment]
By *deparse* do you mean getting back the `SQL` statement?
If so, sure, see the [prettify](https://pglast.readthedocs.io/en/latest/usage.html#programmatically-reformat-a-sql-statement) function.

**Comment by lelit** [comment]
Feel free to reopen, it my answer above is not enough.
