### ISSUE TITLE
Extract tables from the query

### ISSUE THREAD

**Issue by johnchenghk01** [lelit/pglast#66]
How to extract tables from the query like pg_query does?

https://github.com/lfittl/pg_query/blob/master/README.md#extracting-tables-from-a-query

Thanks!

**Comment by lelit** [comment]
I will try to distill a recipe, or an helper method.

**Comment by lelit** [comment]
In the meantime, thanks to @rdunklau, the following does something very close to that:
```python
import pglast
tree = pglast.parse_sql("SELECT ? FROM x JOIN y USING (id) WHERE z = ?")
print([x.relname.value for x in pglast.Node(tree)[0].traverse() if getattr(x, 'node_tag', None) == 'RangeVar'])
```
that emits
```
['x', 'y']
```

**Comment by johnchenghk01** [comment]
Thank you very much!
It will be nice if it can handle `with` clause.

```with x as (select id from tab1) SELECT ? FROM x JOIN tabl2 USING (id) WHERE z = ?```
only emits ```['tab1', 'tab2']```

**Comment by lelit** [comment]
And what did you expect instead?

**Comment by johnchenghk01** [comment]
I expect `['tab1', 'tab2']`, not `['tab1', 'tab2', 'x']`

**Comment by lelit** [comment]
Present in release v3.0.dev1

**Comment by gma2th-jt** [comment]
What is the way to do it in v3.0.dev1? Thanks.

**Comment by lelit** [comment]
For some reasons the documentation at pglast.readthedocs.io/en/latest/visitors.html appears to be empty... will investigate.

In the meantime, this is an example:

```python
>>> from pglast.visitors import referenced_relations
>>> referenced_relations('WITH q1(x,y) AS (SELECT 1,2) SELECT * FROM q1, q2')
{'q2'}
```

PS: we are at v3.3 now.
