### ISSUE TITLE
AST to where clause

### ISSUE THREAD

**Issue by stepan-perlov** [lelit/pglast#69]
Good day!

I interesting in implementation on next task.

I has query, for example

```
EXECUTE QUERY format($$
    SELECT field1, field2, filed3
    FROM table
    %$1s
$$, create_where(whereTree))
```
I interesting on creating whereTree on pglast functionality.
How I can write classes from this lib for generated this:
```
WHERE field1 IS NO NULL
    AND field2 = 'value1'
```

Can I do this with pglast?

**Comment by lelit** [comment]
I'm not sure I understand the goal: do you mean that in some way you build an AST of the expression, and what to use pglast to convert that to its string representation that you eventually pass to the PG procedure?
If so, yes, it's doable, but the hard part is building the AST.
Have you considered using SQLAlchemy instead?

**Comment by stepan-perlov** [comment]
ok, thanks
