### ISSUE TITLE
Parsing / Deparsing of PostgreSQL regress test suite

### ISSUE THREAD

**Issue by rdunklau** [lelit/pglast#73]
In the PostgreSQL test suite, we may encounter statements which are not serialized back to the same form they were originally written. However, the constructions involved are semantically identical.

As for now, I identified the following constuctions detected as different even though they are strictly the same thing.

On TypeName parsing:
- timestamp VS timestamp without time zone
- time VS time without time zone
- ::"char" vs ::char, one being parsed into the name "char" the other one being parsed into pg_catalog.bpchar.
- character VS char(1) 
- bit varying VS varbit

I will update this list as I found other issues.

**Comment by lelit** [comment]
See the `libpg_query` [deparseTypeName()](https://github.com/pganalyze/libpg_query/blob/13-latest/src/pg_query_deparse.c#L3259) function.

**Comment by lelit** [comment]
I'm not sure if there is still something to do here, as all the regression tests pass now.
Can you check and clarify please?
