### ISSUE TITLE
Change DDL caveat in README

### ISSUE THREAD

**Issue by pauldraper** [lelit/pglast#75]
README says

> Currently this covers most DML statements such as SELECTs, INSERTs, DELETEs and UPDATEs, fulfilling my needs, but I'd like to extend it to handle also DDL statements and, why not, PLpgSQL instructions too.

It actually seems like most DDL is covered.

**Comment by lelit** [comment]
Thank you: in the currently work-in-progress v3 branch there is an ongoing effort to handle all the "regression" test suite that comes from PG thru libpg_query, so I'll surely tweak that statement once we get there.

**Comment by lelit** [comment]
I just released the first version of v3, the README has been updated.
