### ISSUE TITLE
Build error re xxhash headers on non-wheel pip install

### ISSUE THREAD

**Issue by djrobstep** [lelit/pglast#82]
When I try to install this package without using a pre-built wheel (such as on macos where there are no wheels on pypi) I get a build error relating to xxhash headers. If install from a local folder, it works fine.

**Comment by lelit** [comment]
Oh, thanks for the report: that seems a problem with the MANIFEST.in file, that should include the `libpg_query/vendor` directory.

**Comment by lelit** [comment]
I'm sorry, but just released v3.1 do **not** fix this issue, but v3.2 will do.

**Comment by lelit** [comment]
I released v3.2 to really fix this.
