### ISSUE TITLE
Licensing question -- use in testing

### ISSUE THREAD

**Issue by dargueta** [lelit/pglast#83]
I know this is somewhat of a duplicate of issue #9, but I'd like to ask for a clarification.

My employer would like to use this library in our CI test suite merely as a linter for our ETL's SQL scripts; it's not even installed in production. Neither our ETL nor the test suite are publicly available. Would this be an acceptable usage?

**Comment by lelit** [comment]
Sure it is.

**Comment by dargueta** [comment]
Good to know. Thanks for the quick response!
