### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [lelit/pglast#94]
Problem
---------
On aarch64, `pip install pglast` builds the wheels from source code and then installs it. It requires the user to have a development environment installed on their system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPI.

Resolution
-----------
On aarch64, `pip install pglast` should download the wheels from PyPI.

@lelit, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by lelit** [comment]
Sure, much appreciated, thanks!

**Comment by lelit** [comment]
Other than taking so looong to compile everything, this is now fixed.
